### ISSUE TITLE
This just happened randomly during my game.

### ISSUE THREAD

**Issue by Hoverboard47** [relaxtakenotes/universal-screen-shake#1]
[Recoil Screen Shake] lua/autorun/client/universal_screen_shake.lua:189: attempt to index local 'base_view' (a nil value)
    1. fn - lua/autorun/client/universal_screen_shake.lua:189
        2. unknown - lua/ulib/shared/hook.lua:109 Didnt really affect anything and i didnt find a difference, waiting a few seconds made the error go away

**Comment by relaxtakenotes** [comment]
seems like a harmless bug. i'll do some basic checks to prevent it though
