### ISSUE TITLE
Smooth Out Stairs + Enhanced Recoil + Shmovment incompatibility

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/universal-screen-shake#12]
There's no repo for Smooth Out Stairs, so... Narrowed it down to a specific combination - Smooth Out Stairs, Enhanced Recoil, and Shmovment (with literally only these three installed)
There's weird vm floatiness when crouching/moving vertically AND while in horizontal motion for the duration of Enhanced Recoil 'effect':

https://github.com/relaxtakenotes/universal-screen-shake/assets/75931669/c675fb12-37c3-4479-b1a9-1bb0a90ec416

I know you said it's not really possible to resolve conflicts between Shmovment and other CalcView-based addons, but even if it's definitive in the current case, let this be at least a warning to some folks. Basically, this vm bug only exists when All Three of these addons are active. Should you disable one of them (even cvars are good) and the issue goes away

P.S. It's the same even for HL2 weapons btw

**Comment by relaxtakenotes** [comment]
i'm way too tired from having to resolve calcview conflicts.

**Comment by relaxtakenotes** [comment]
pushed an experimental fix to smooth out stairs which should work nicely with these mods. if it works without a hitch then the fix will end up in my other mods where calcview appears.

**Comment by Lombaxtard** [comment]
> pushed an experimental fix to smooth out stairs which should work nicely with these mods. if it works without a hitch then the fix will end up in my other mods where calcview appears.

This combo works for me now, thanks a lot!
I really appreciate you trying to fix CalcView-related issues nonetheless. It is my understanding that it's one hell of a <"system",> a real crybaby (18+) when it comes to touching it in interesting (or at all) ways with lua. And it's that one thing developers unanimously refer to as being "consistently shit" to work with
P.S. To be really honest here, from experience your firstperson-related stuff is the most thing compatible out there, really hard to break (unless with some weird addon combinations or just outright poorly coded mods)

**Comment by relaxtakenotes** [comment]
there are certain values that you can't change in calcview without returning from the hook, and returning means you disregard other hooks left in the queue. so to mitigate that we can run all the hooks ourselves before returning, but then it means we can run into a different mod that also does the same trick and thus the same hook can be run multiple times. THAT is why i hate it. however as we can see here, it's fixable, so i'll go ahead and push the same stinky fix to my other mods
