### ISSUE TITLE
TFA base ADS zoom issue

### ISSUE THREAD

**Issue by AlanFazzy** [relaxtakenotes/universal-screen-shake#2]
Hi
So there was an issue with Universal Recoil Screen Shake on TFA base, when ever you are shooting guns in ADS fov zooms to 0 and it stands like that a few seconds and then resets to default, while hip fire is fine. Tested without any mods that may touch viewbob, idk what's the reason here, i think you might want to have a look. 
To note - yes, it's still the same with forced compatibility mode, thanks for attention. 
clip for full representation, only weapons and RSS
https://github.com/relaxtakenotes/universal-screen-shake/assets/88910369/13933c6e-284a-4523-80b5-26607b65035e

**Comment by relaxtakenotes** [comment]
actually if anything you need to disable compatibility mode with tfa, because ironically the most compatible method breaks it. send me a collection of your mods so i can replicate the issue

**Comment by AlanFazzy** [comment]
Here, i didn't include everything cuz collection was gonna ne weighty (up to 10gb's) but i think and one small mod, thanks for reply
collection: https://steamcommunity.com/sharedfiles/filedetails/?id=3045167192

**Comment by relaxtakenotes** [comment]
should be fixed in the newest version
