### ISSUE TITLE
An issue when using mighty foot engaged kicks

### ISSUE THREAD

**Issue by WaWa574** [relaxtakenotes/universal-screen-shake#4]
when I use mighty foot engaged kicks with this mod, my leg animation wont appear, but the damage and the effects are done normally. any idea to fix this?

**Comment by AlanFazzy** [comment]
Try to force compatibility mode, it helped for me but there might be a lua error pop up.

**Comment by relaxtakenotes** [comment]
^ that. i'll see if there's another way to fix it or of i need to force compatibility mode for it
