### ISSUE TITLE
Setting a custom "cl_screenshake_set_custom_mult" value ends up with errors

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/universal-screen-shake#6]
Got around to try this command, but a constant error turned up the instant I've added a classname with a value:

lua/autorun/client/!!!!!!!!!!!!universal_screen_shake.lua:264: attempt to perform arithmetic on local 'custom_shake' (a nil value)
  1. on_primary_attack - lua/autorun/client/!!!!!!!!!!!!universal_screen_shake.lua:264
   2. fn - lua/autorun/client/!!!!!!!!!!!!universal_screen_shake.lua:287
    3. unknown - lua/ulib/shared/hook.lua:109

I tried USS with <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2977764069">this</a>. Error disappears once I "reload" another one in/cl_screenshake_reset_custom_mult in the moment

**Comment by relaxtakenotes** [comment]
should be fixed now

**Comment by relaxtakenotes** [comment]
nvm it's not

**Comment by relaxtakenotes** [comment]
now it should be lol jeez
